load microcode module on package install/upgrade
When the package is first installed, manually loading the microcode
module might be necessary to be able to update the microcode without a
reboot.

Should we succeed to load the microcode module, there is no need to
manually trigger a microcode update, as the module load will trigger it
by itself.

Also add a script to make sure the microcode module is loaded before
kernel updates, otherwise we will require a reboot before we can update
the microcode once again...

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -19,20 +19,27 @@ set -e
 
 case "$1" in
     configure)
-	if [ -e /sys/devices/system/cpu/microcode/reload ] ; then
+	# try to load the microcode module just in case.  If we succeed,
+	# it will trigger a microcode update by itself
+	if modprobe -q --first-time microcode ; then
 	    echo "Updating microcode on all online processors..." >&2
-	    echo 1 > /sys/devices/system/cpu/microcode/reload || {
-	        echo "Kernel reported failure while updating microcode!" >&2
-            }
 	else
-	    # Try all online processors, broken kernels need this,
-	    # fixed kernels will accept it only on the BSP and update
-	    # all processors anyway, and -EINVAL all others... but we
-	    # don't know which one is the BSP, so we try all of them
-	    # and hide errors, the kernel will log any real problem.
-	    echo "Using per-core interface to update microcode on online processors..." >&2
-	    find /sys/devices/system/cpu -noleaf -type f -path '/sys/devices/system/cpu/cpu*/microcode/reload' | \
-		while read i ; do echo -n 1 2>/dev/null >"$i" || true ; done
+	    # we have to trigger the microcode update manually
+	    if [ -e /sys/devices/system/cpu/microcode/reload ] ; then
+		echo "Updating microcode on all online processors..." >&2
+		echo 1 > /sys/devices/system/cpu/microcode/reload || {
+		    echo "Kernel reported failure while updating microcode!" >&2
+		}
+	    else
+		# Try all online processors, broken kernels need this,
+		# fixed kernels will accept it only on the BSP and update
+		# all processors anyway, and -EINVAL all others... but we
+		# don't know which one is the BSP, so we try all of them
+		# and hide errors, the kernel will log any real problem.
+		echo "Using per-core interface to update microcode on online processors..." >&2
+		find /sys/devices/system/cpu -noleaf -type f -path '/sys/devices/system/cpu/cpu*/microcode/reload' | \
+		    while read i ; do echo -n 1 2>/dev/null >"$i" || true ; done
+	    fi
 	fi
 	# do it like udev and firmware-linux-*
 	if [ -x /usr/sbin/update-initramfs -a -e /etc/initramfs-tools/initramfs.conf ] ; then
