initramfs, postinst: don't do anything on non-AMD systems
Don't trigger microcode updates, nor install microcode to the initramfs
on systems that don't have an AuthenticAMD processor (according to
/proc/cpuinfo vendor_id field).

Closes: #715518

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -19,21 +19,24 @@ set -e
 
 case "$1" in
     configure)
-	if [ -e /sys/devices/system/cpu/microcode/reload ] ; then
-	    echo "Updating microcode on all online processors..." >&2
-	    echo 1 > /sys/devices/system/cpu/microcode/reload || {
-	        echo "Kernel reported failure while updating microcode!" >&2
-            }
-	else
-	    # Try all online processors, broken kernels need this,
-	    # fixed kernels will accept it only on the BSP and update
-	    # all processors anyway, and -EINVAL all others... but we
-	    # don't know which one is the BSP, so we try all of them
-	    # and hide errors, the kernel will log any real problem.
-	    echo "Using per-core interface to update microcode on online processors..." >&2
-	    find /sys/devices/system/cpu -noleaf -type f -path '/sys/devices/system/cpu/cpu*/microcode/reload' | \
-		while read i ; do echo -n 1 2>/dev/null >"$i" || true ; done
-	fi
+	grep -q "^vendor_id[[:blank:]]*:[[:blank:]]*.*AuthenticAMD" /proc/cpuinfo && {
+	    if [ -e /sys/devices/system/cpu/microcode/reload ] ; then
+		echo "Updating microcode on all online processors..." >&2
+		echo 1 > /sys/devices/system/cpu/microcode/reload || {
+		    echo "Kernel reported failure while updating microcode!" >&2
+		}
+	    else
+		# Try all online processors, broken kernels need this,
+		# fixed kernels will accept it only on the BSP and update
+		# all processors anyway, and -EINVAL all others... but we
+		# don't know which one is the BSP, so we try all of them
+		# and hide errors, the kernel will log any real problem.
+		echo "Using per-core interface to update microcode on online processors..." >&2
+		find /sys/devices/system/cpu -noleaf -type f -path '/sys/devices/system/cpu/cpu*/microcode/reload' | \
+		    while read i ; do echo -n 1 2>/dev/null >"$i" || true ; done
+	    fi
+        }
+
 	# do it like udev and firmware-linux-*
 	if [ -x /usr/sbin/update-initramfs -a -e /etc/initramfs-tools/initramfs.conf ] ; then
 		update-initramfs -u
